name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - opened
    branches:
      - '**'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag the package
        run: |
          git config --global user.email "raj7.eie@gmail.com"
          git config --global user.name "Anand Raj"
          git tag -a v1.0 -m "Version 1.0"
          git push origin v1.0
